id: IB54ABDC7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T14:21:57+00:00'
last_modified: '2022-06-08T01:46:31.276853+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD137810
  title: དབུས་འཛིན་གྱི་གཞུང་། ༼རྒྱ་བོད་ཤན་སྦྱར།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    8F37:
      image_group_id: I2PD19676
      title: ''
      total_pages: 100
      order: 1
      base_file: 8F37.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
