id: P004536
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1PD137810
  title: དབུས་འཛིན་གྱི་གཞུང་། ༼རྒྱ་བོད་ཤན་སྦྱར།༽
  author: ''
  volumes:
    9e1a0ced80744edf909769570ceb4c0b:
      image_group_id: I2PD19676
      title: ''
      volume_number: 1
      total_pages: 100
      base_file: v001.txt
